### ISSUE TITLE
conveyor belt

### ISSUE THREAD

**Issue by joheko** [Spiros-Dimitriou/Dobot-Gregor-Chair#1]
hey! Did you try to use conveyor belt? i don't make it rotate.

**Comment by spyrosdim** [comment]
Greetings! I assume you mean the sliding rail that the Dobot Magician can sit on. We don't have one so we simulated that by simply moving the arm. Although you might want to look at this command: https://github.com/AlexGustafsson/dobot-python/blob/a7a3281399bae491f9ac34ecdcd06edbd103538b/lib/interface.py#L240

Alex's API has proved to be pretty helpful.
